name: 'Docvet Check'
description: 'Comprehensive docstring quality checks — completeness, freshness, rendering, and coverage for Python projects'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  version:
    description: 'docvet version to install (use "latest" for newest)'
    required: false
    default: 'latest'
  args:
    description: 'Arguments to pass to docvet (e.g., "check --all")'
    required: false
    default: 'check'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Install docvet
      env:
        DOCVET_VERSION: ${{ inputs.version }}
      run: |
        if [ "$DOCVET_VERSION" = "latest" ]; then
          pip install docvet
        else
          pip install "docvet==$DOCVET_VERSION"
        fi
      shell: bash
    - name: Run docvet
      env:
        DOCVET_ARGS: ${{ inputs.args }}
      run: docvet $DOCVET_ARGS
      shell: bash
