# Codecov configuration for docvet
# See: https://docs.codecov.com/docs/codecovyml-reference

codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1  # Only 1 matrix cell uploads coverage (ubuntu/3.12)

coverage:
  status:
    project:
      default:
        target: 85%  # Matches CI --cov-fail-under=85
        threshold: 2%
    patch:
      default:
        target: 80%  # New code should maintain coverage

comment:
  layout: "reach,diff,files"
  behavior: default
  require_changes: false
